CafeJWTMVC/Controllers/CafeCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Models;
using Data;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace CafeJWTMVC.Controllers
{
    [Authorize]
    public class CafeCommentsController : Controller
    {
        private readonly ApplicationDBContext _context;

        public CafeCommentsController(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: CafeComments
        public static string baseUrl = "http://localhost:62049/api/cafecomments/";
        public async Task<IActionResult> Index()
        {
            var products = await GetProducts();
            return View(products);
        }

        [HttpGet]
        public async Task<List<CafeComment>> GetProducts()
        {
            // Use the access token to call a protected web API.
            var accessToken = HttpContext.Session.GetString("JWToken");
            var url = baseUrl;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonStr = await client.GetStringAsync(url);


            var res = JsonConvert.DeserializeObject<List<CafeComment>>(jsonStr).ToList();

            return res;
        }

       public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var accessToken = HttpContext.Session.GetString("JWToken");
            var url = baseUrl + id;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);

            string jsonStr = await client.GetStringAsync(url);
            var res = JsonConvert.DeserializeObject<CafeComment>(jsonStr);

            if (res == null)
            {
                return NotFound();
            }
            return View(res);
        }

        // POST: CafeComments/Delete/5
       [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            var url = baseUrl + id;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            await client.DeleteAsync(url);
            return RedirectToAction(nameof(Index));
        }

        private bool CafeCommentExists(int id)
        {
            return _context.CafeComments.Any(e => e.Id == id);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(CafeCommentViewModel vm)
        {
            var comment = vm.Comment;
            var cafeId = vm.CafesId;
            var rating = vm.Rating;

            CafeComment cafcomment = new CafeComment()
            {
                CafesId = cafeId,
                Comments = comment,
                Rating = rating,
                PublishedDate = DateTime.Now
            };

            _context.CafeComments.Add(cafcomment);
            _context.SaveChanges();

            return RedirectToAction("Details", "Cafes1", new { id = cafeId });

        }

    }
}

CafeJWTMVC/Controllers/Cafes1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Models;
using Data;
using Microsoft.AspNetCore.Authorization;

namespace CafeJWTMVC.Controllers
{
    [Authorize]
    public class Cafes1Controller : Controller
    {
        private readonly ApplicationDBContext _context;

        public Cafes1Controller(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: Cafes1
        public async Task<IActionResult> Index()
        {
            var applicationDBContext = _context.Cafe.Include(c => c.Produtor).Include(c => c.Regiao);
            return View(await applicationDBContext.ToListAsync());
        }

        // GET: Cafes1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            Cafe cafe = _context.Cafe.Find(id);
            CafeCommentViewModel vm = new CafeCommentViewModel();

            if (cafe == null)
            {
                return NotFound();
            }
            vm.CafesId = id.Value;
            vm.NomeCafe = cafe.NomeCafe;
            var Comments = _context.CafeComments.Where(d => d.CafesId.Equals(id.Value)).ToList();
            vm.ListOfComments = Comments;

            var ratings = _context.CafeComments.Where(d => d.CafesId.Equals(id.Value)).ToList();
            if (ratings.Count() > 0)
            {
                var ratingSum = ratings.Sum(d => d.Rating);
                ViewBag.RatingSum = ratingSum;
                var ratingCount = ratings.Count();
                ViewBag.RatingCount = ratingCount;
            }
            else
            {
                ViewBag.RatingSum = 0;
                ViewBag.RatingCount = 0;
            }
            return View(vm);
        }

        // GET: Cafes1/Create
        public IActionResult Create()
        {
            ViewData["ProdutorId"] = new SelectList(_context.Produtor, "ProdutorId", "ProdutorId");
            ViewData["RegiaoId"] = new SelectList(_context.Regiao, "RegiaoId", "RegiaoId");
            return View();
        }

        // POST: Cafes1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomeCafe,Nota,Impressoes,PublishedDate,ProdutorId,RegiaoId")] Cafe cafe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cafe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdutorId"] = new SelectList(_context.Produtor, "ProdutorId", "ProdutorId", cafe.ProdutorId);
            ViewData["RegiaoId"] = new SelectList(_context.Regiao, "RegiaoId", "RegiaoId", cafe.RegiaoId);
            return View(cafe);
        }

        // GET: Cafes1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cafe = await _context.Cafe.FindAsync(id);
            if (cafe == null)
            {
                return NotFound();
            }
            ViewData["ProdutorId"] = new SelectList(_context.Produtor, "ProdutorId", "ProdutorId", cafe.ProdutorId);
            ViewData["RegiaoId"] = new SelectList(_context.Regiao, "RegiaoId", "RegiaoId", cafe.RegiaoId);
            return View(cafe);
        }

        // POST: Cafes1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NomeCafe,Nota,Impressoes,PublishedDate,ProdutorId,RegiaoId")] Cafe cafe)
        {
            if (id != cafe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cafe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CafeExists(cafe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdutorId"] = new SelectList(_context.Produtor, "ProdutorId", "ProdutorId", cafe.ProdutorId);
            ViewData["RegiaoId"] = new SelectList(_context.Regiao, "RegiaoId", "RegiaoId", cafe.RegiaoId);
            return View(cafe);
        }

        // GET: Cafes1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cafe = await _context.Cafe
                .Include(c => c.Produtor)
                .Include(c => c.Regiao)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cafe == null)
            {
                return NotFound();
            }

            return View(cafe);
        }

        // POST: Cafes1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cafe = await _context.Cafe.FindAsync(id);
            _context.Cafe.Remove(cafe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CafeExists(int id)
        {
            return _context.Cafe.Any(e => e.Id == id);
        }
    }
}

CafeJWTMVC/Controllers/DashboardController.cs
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CafeJWTMVC.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly UserManager<UserInfo> userManager;

        public DashboardController(UserManager<UserInfo> userManager)
        {
            this.userManager = userManager;
        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = userManager.Users;
            return View(users);
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

CafeJWTMVC/Controllers/Midias1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Core.Models;
using Data;
using Microsoft.AspNetCore.Http;
using Microsoft.WindowsAzure.Storage;
using Microsoft.Data.SqlClient;
using System.Data;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace CafeJWTMVC.Controllers
{
    [Authorize]
    public class Midias1Controller : Controller
    {
        public static string baseUrl = "http://localhost:62049/api/midias/";

        private readonly ApplicationDBContext _context;

        public Midias1Controller(ApplicationDBContext context)
        {
            _context = context;
        }

        // GET: Midias1
        public async Task<IActionResult> Index()
        {

            var products = await GetAll();
            return View(products);
        }

        [HttpGet]
        public async Task<List<Midia>> GetAll()
        {
            var accessToken = HttpContext.Session.GetString("JWToken");
            var url = baseUrl;
            HttpClient client = new HttpClient();
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            string jsonStr = await client.GetStringAsync(url);

            var res = JsonConvert.DeserializeObject<List<Midia>>(jsonStr).ToList();

            return res;

        }
        // GET: Midias1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var midia = await _context.Midia
                .FirstOrDefaultAsync(m => m.MidiasId == id);
            if (midia == null)
            {
                return NotFound();
            }

            return View(midia);
        }

        // GET: Midias1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Midias1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Midia pais)
        {
            var Foto = UploadBlob(pais.Imagem);
            if (ModelState.IsValid)
            {
                var connectionString = "Server = (localdb)\\mssqllocaldb; Database = CafeJWTMVC; Trusted_Connection = True; MultipleActiveResultSets = true";
                SqlConnection connection = new SqlConnection(connectionString);
                {
                    var storedprocedure = "CadastrarMidias";
                    var sqlCommand = new SqlCommand(storedprocedure, connection);
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.Parameters.AddWithValue("@Foto", await Foto);
                    try
                    {
                        connection.Open();
                        sqlCommand.ExecuteNonQuery();
                    }
                    finally
                    {
                        connection.Close();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pais);
        }


        // GET: Midias1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var midia = await _context.Midia.FindAsync(id);
            if (midia == null)
            {
                return NotFound();
            }
            return View(midia);
        }

        // POST: Midias1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MidiasId,Foto")] Midia midia)
        {
            if (id != midia.MidiasId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(midia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MidiaExists(midia.MidiasId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(midia);
        }

        // GET: Midias1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var midia = await _context.Midia
                .FirstOrDefaultAsync(m => m.MidiasId == id);
            if (midia == null)
            {
                return NotFound();
            }

            return View(midia);
        }

        // POST: Midias1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var midia = await _context.Midia.FindAsync(id);
            _context.Midia.Remove(midia);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MidiaExists(int id)
        {
            return _context.Midia.Any(e => e.MidiasId == id);
        }

        public async Task<string> UploadBlob(IFormFile imageFile)
        {

            var reader = imageFile.OpenReadStream();
            var cloundStorageAccount = CloudStorageAccount.Parse(@"DefaultEndpointsProtocol=https;AccountName=igorsouza0489;AccountKey=bvr5caFtow9DNwVRtfPZZetD+WM1XG7dqbG1R/AxscBAkmvT12xoqDRg+T8ZL6DULmBWCd+4U9mS+AStnnryYw==;EndpointSuffix=core.windows.net");
            var blobClient = cloundStorageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("imagecontainer");
            await container.CreateIfNotExistsAsync();
            var blob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            await blob.UploadFromStreamAsync(reader);
            var uri = blob.Uri.ToString();
            return uri;
        }
    }
}

CafeJWTMVC/Views/Shared/CafeCommentBox.cshtml
@model Core.Models.CafeCommentViewModel
<dl class="dl-horizontal">
    <dt>
        Comment
    </dt>


    <dd>
        <div class="commentBox">
            @using (Html.BeginForm("Add", "CafeComments", FormMethod.Post, new { onsubmit = "return SubmitComment()" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-4 custom-control-label">
                            Clique abaixo para dar sua nota <span style="font-weight:bold;">(1 a 5)</span>
                        </label>
                        <div class="col-md-7">
                            <div onmouseout="CRateSelected()">
                                <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseout="CRateOut(1)"></span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseout="CRateOut(2)"></span><span class="starFade" id="Rate3" onclick="CRate(3)" onmouseout="CRateOut(3)"></span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseout="CRateOut(4)"></span><span class="starFade" id="Rate5" onclick="CRate(5)" onmouseout="CRateOut(5)"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea asp-for="Comment" required rows="5" style="width:100%;" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="hidden" asp-for="CafesId" />

                            <input type="hidden" name="Rating" id="Rating" value="0" />
                            <input type="submit" id="btnRegister" name="btnRegister" value="Submit Comment" class="btn btn-dark" style="background-color: sandybrown !important; border: solid" />

                        </div>
                    </div>



                </div>
            }

        </div>
    </dd>
</dl>
<script>
    function SubmitComment() {
        if ($("#Rating").val() == "0") {
            alert("Please rate this service provider.");
            return false;
        }
        else {
            return true;
        }
    }

    function CRate(r) {
        $("#Rating").val(r);
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
        for (var i = r + 1; i <= 5; i++) {
            $("#Rate" + i).attr('class', starFade);
        }
    }

    function CRateOver(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', starGlow);
        }
    }

    function CRateOut(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateSelected() {
        var setRating = $("#Rating").val();
        for (var i = 1; i <= setRating; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }

</script>

CafeJWTMVC/Views/Shared/View.cshtml
@model Core.Models.CafeCommentViewModel

@{
    var ratingSum = ViewBag.RatingSum;
    var ratingCount = ViewBag.RatingCount;

    decimal rating = 0;
    if (ratingCount > 0)
    {
        rating = (ratingSum / ratingCount);
    }
    var totalRating = decimal.Parse(rating.ToString());
}

<h1>@Model.NomeCafe</h1>

<!---<div>
    <span class="starFadeN" id="sRate1"></span><span class="starFadeN" id="sRate2"></span><span class="starFadeN" id="sRate3"></span><span class="starFadeN" id="sRate4"></span><span class="starFadeN" id="sRate5"></span>
</div>-->
@foreach (var c in Model.ListOfComments)
{
    <hr />
    <div class="row">
        <div class="col-md-3">
            <i>@c.PublishedDate</i>
            <br />
            @for (var i = 1; i <= c.Rating; i++)
            {
                <span class="starGlowN"></span>
            }
            @for (var i = (c.Rating + 1); i <= 5; i++)
            {
                <span class="starFadeN"></span>
            }
        </div>
        <div class="col-md-9">
            @Html.Raw(c.Comments.Replace("\n", "<br />"))

        </div>
    </div>
}

<hr />
<partial name="CafeCommentBox" />
<div>
    <a asp-action="Index">Voltar para lista de cafés</a>
</div>
<script>
    function SCRate() {
        for (var i = 1; i <= @totalRating; i++) {
            $("#sRate" + i).attr('class', 'starGlowN');
        }
    }
    $(function () {
        SCRate();

    });
</script>

<style>

    .dl-horizontal dt {
        white-space: normal;
    }

    input,
    select,
    textarea {
        max-width: 280px;
    }

    .custom-control-label::before {
        display: none !important;
    }

    .commentBox {
        background-color: white;
        padding: 10px;
        border-radius: 10px;
    }




    .starFade {
        background-color: grey;
        min-width: 30px;
        min-height: 30px;
        display: inline-block;
        cursor: pointer;
    }

    .starFadeN {
        background-color: grey;
        min-width: 30px;
        min-height: 30px;
        display: inline-block;
    }

    .starGlow {
        background-color: yellow;
        min-width: 30px;
        min-height: 30px;
        display: inline-block;
        cursor: pointer;
    }

    .starGlowN {
        background-color: yellow;
        min-width: 30px;
        min-height: 30px;
        display: inline-block;
    }
</style>

CafeJWTMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@using Core.Models

@inject SignInManager<UserInfo> SignInManager
@inject UserManager<UserInfo> UserManager

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] AmantesCafé </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3"  style="background-color: #865533 !important; border:hidden">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Cafes1" asp-action="Index"><img src="https://storagevik.blob.core.windows.net/cafecontainer/LogoAmantesCafe.png" width="100" height="100" align="left" /></a>

                <a class="nav-link text-white" asp-area="" asp-controller="Dashboard" asp-action="listusers">Usuários</a>
                <a class="nav-link text-white" asp-area="" asp-controller="Regiaos" asp-action="Index">Regiões</a>
                <a class="nav-link text-white" asp-area="" asp-controller="Produtors" asp-action="Index">Produtores</a>
                <a class="nav-link text-white" asp-area="" asp-controller="Cafes1" asp-action="Index">Cafés</a>
                <a class="nav-link text-white" asp-area="" asp-controller="Cafecomments" asp-action="Index">Comentários</a>
                <a class="nav-link text-white" asp-area="" asp-controller="Midias1" asp-action="Index">Mídias</a>




                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial.cshtml" />

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CafeJWTMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>